# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "bootstrap"
        versions: [">= 5.2", "< 6"]
      - dependency-name: "rails"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: master # additional config for bundler, see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    schedule:
      interval: "monthly"
    versioning-strategy: increase-if-necessary
    labels:
      - "manually"
    ignore:
      - dependency-name: "bootstrap"
        versions: [">= 5.2", "< 6"]
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
