# frozen_string_literal: true

# Move this require to your `config/application.rb` if you want to be notified from runner commands too.
require "exception_notification/rails"
require "exception_notification/rake"

require Rails.root.join('app/modules/config.rb').to_s
mailer_cfg = Config.for(:mailer)

ExceptionNotification.configure do |config|
  # Ignore additional exception types. The default list of exception classes is:
  #   ActiveRecord::RecordNotFound Mongoid::Errors::DocumentNotFound AbstractController::ActionNotFound
  #   ActionController::RoutingError ActionController::UnknownFormat ActionController::UrlGenerationError
  #   ActionDispatch::Http::MimeNegotiation::InvalidType Rack::Utils::InvalidParameterError
  # config.ignored_exceptions += %w[ActionView::TemplateError CustomError]

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  config.ignore_if do |exception, options| # rubocop:disable Lint/UnusedBlockArgument
    # Rails.env.local? # use for both env: test and development
    Rails.env.development?
  end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w[Googlebot bingbot]

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: "[KS-Backoffice Exception] ",
    sender_address: ["\"Klarschiff-Backoffice (#{Rails.env})\" <#{mailer_cfg[:default][:from]}>"],
    exception_recipients: mailer_cfg[:default][:exceptions_recipient],
    email_headers: { 'X-Override-Consolidation': true }
  }

  # Campfire notifier sends notifications to your Campfire room. Requires "tinder" gem.
  # config.add_notifier :campfire, {
  #   subdomain: "my_subdomain",
  #   token: "my_token",
  #   room_name: "my_room"
  # }

  # HipChat notifier sends notifications to your HipChat room. Requires "hipchat" gem.
  # config.add_notifier :hipchat, {
  #   api_token: "my_token",
  #   room_name: "my_room"
  # }

  # Webhook notifier sends notifications over HTTP protocol. Requires "httparty" gem.
  # config.add_notifier :webhook, {
  #   url: "http://example.com:5555/hubot/path",
  #   http_method: :post
  # }
end
