development: &default
  media_base_url: https://www.klarschiff-hro.de
  discovery_changeset: 2015-11-05 08:43
  discovery_contact: "Hanse- und Universitätsstadt Rostock, Kataster-, Vermessungs- und Liegenschaftsamt, Holbeinplatz 14, 18069 Rostock, klarschiff.hro@rostock.de"
  discovery_key_service: klarschiff.hro@rostock.de
  discovery_endpoints:
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://geo.sv.rostock.de/citysdk
      changeset: 2015-11-05 08:43
      type: production
      formats:
        - application/json
        - text/xml
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://support.klarschiff-hro.de/citysdk
      changeset: 2015-11-05 08:43
      type: test
      formats:
        - application/json
        - text/xml
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://demo.klarschiff-hro.de/citysdk
      changeset: 2015-11-05 08:43
      type: test
      formats:
        - application/json
        - text/xml

alpha: *default

consolidation: *default

production: *default

test: *default
