
development: &default
  d3:
    api: http://musterstadt-d3-host.org/codiaDMSService/codiaDMSService.asmx
    check_existence: /StartSearch?strDDC=%{ddc}&strFieldsAndValues=Klarschiff-ID=%{issue_id}
    create:
      AAUTO: http://musterstadt-d3-host.org/create-link/?ks_id=%{ks_id}&ks_user=%{ks_user}&ks_str=%{ks_str}&ks_hnr=%{ks_hnr}&ks_hnr_z=%{ks_hnr_z}&ks_eigentuemer=%{ks_eigentuemer}
    proxy_host:
    proxy_port:
    reset_search: /CloseSearch?strDDC=%{ddc}&strFieldsAndValues=Klarschiff-ID=%{issue_id}
    show: /GetNthDOKID?strDDC=%{ddc}&strFieldsAndValues=Klarschiff-ID=%{issue_id}&iIndex=1

alpha: *default

consolidation: *default

production: *default

test: *default
