development: &default
  config:
    levels:
      - level: 1
        days_created_not_in_work: 10
        days_in_work_without_status_note: 10
        days_open_but_not_accepted: 10
        days_open_ideas_without_minimum_supporters: 30
        reviewed_but_not_accepted: true
        unsolvable_without_status_note: true
        without_editorial_approval: true
      - level: 2
        days_created_not_in_work: 20
        days_in_work_without_status_note: 20
        days_open_but_not_accepted: 10
        days_open_ideas_without_minimum_supporters: 10
        reviewed_but_not_accepted: true
        unsolvable_without_status_note: true
        without_editorial_approval: false
      - level: 3
        days_created_not_in_work: 10
        days_in_work_without_status_note: 10
        days_open_but_not_accepted: 10
        days_open_ideas_without_minimum_supporters: 30
        reviewed_but_not_accepted: false
        unsolvable_without_status_note: false
        without_editorial_approval: false
test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
