development: &default
  abuse:
    deletion_deadline_days: 1
  issue:
    delegation_deadline_days: 1
    deletion_deadline_days: 1
    archival_deadline_days: 30
    author_deletion_deadline_days: 1
    author_deletion_replacement: '- bei Archivierung entfernt -'
    status_change_days: 1
  photo:
    deletion_deadline_days: 1
  support:
    deletion_deadline_days: 1

consolidation: *default

production: *default

test: *default
