versions:
  ol: 6.14.1
  proj4: 2.7.5
  tablednd: 1.0.3

javascripts:
  ol.js: https://raw.githubusercontent.com/openlayers/openlayers.github.io/main/dist/en/v<%= versions[:ol] %>/build/ol.js
  proj4js.js: https://cdnjs.cloudflare.com/ajax/libs/proj4js/<%= versions[:proj4] %>/proj4.js
  tablednd.js: https://cdnjs.cloudflare.com/ajax/libs/TableDnD/<%= versions[:tablednd] %>/jquery.tablednd.min.js

stylesheets:
  ol.css: https://raw.githubusercontent.com/openlayers/openlayers.github.io/main/dist/en/v<%= versions[:ol] %>/css/ol.css
