versions:
  ol: 7.5.1
  proj4: 2.9.0
  tablednd: 1.0.3

javascripts:
  ol.js: https://cdn.jsdelivr.net/npm/ol@v<%= versions[:ol] %>/dist/ol.js
  proj4js.js: https://cdn.jsdelivr.net/npm/proj4@<%= versions[:proj4] %>/dist/proj4.js
  tablednd.js: https://cdnjs.cloudflare.com/ajax/libs/TableDnD/<%= versions[:tablednd] %>/jquery.tablednd.min.js

stylesheets:
  ol.css: https://cdn.jsdelivr.net/npm/ol@v<%= versions[:ol] %>/ol.css
