development: &default
  confirmation_base_url: https://www.klarschiff-mv.de/confirmations
  default:
    from: from@example.com
    interceptions_recipient: support-klarschiff@bfpi.de
  issue_mailer:
    forward:
      subject: weitergeleiteter Vorgang
    issue:
      subject: weitergeleiteter Vorgang aus dem Beteiligungsportal Klarschiff von Schwerin
  confirmation_mailer:
    abuse_report:
      subject: "#%{number}: Bestätigung einer Missbrauchsmeldung"
    issue:
      subject: "#%{number}: Meldungsbestätigung"
    photo:
      subject: "#%{number}: Bestätigung eines Fotos"
    supporter:
      subject: "#%{number}: Bestätigung einer Unterstützung"
  feedback_mailer:
    notification:
      to: support-klarschiff@bfpi.de
      subject: "Lob/Hinweis/Kritik zur Meldung #%{number}"
  issue_mailer:
    in_process:
      subject: "#%{number}: in Bearbeitung"
    closed:
      subject: "#%{number}: abgeschlossen"
    delegation:
      subject: "Neue delegierte Vorgänge"
    inform_editorial_staff:
      subject: "%{title}: wichtige redaktionelle Hinweise"
  test_mailer:
    test:
      subject: Test-Mail

consolidation: *default

production: *default

test: *default
