development: &default
  confirmation_base_url: https://www.klarschiff-mv.de/confirmations
  default:
    from: from@example.com
    exceptions_recipient: support-klarschiff@bfpi.de
    interceptions_recipient: support-klarschiff@bfpi.de
  confirmation_mailer:
    abuse_report:
      subject: "#%{number}: Bestätigung einer Missbrauchsmeldung"
    issue:
      subject: "#%{number}: Meldungsbestätigung"
    photo:
      subject: "#%{number}: Bestätigung eines Fotos"
    supporter:
      subject: "#%{number}: Bestätigung einer Unterstützung"
  feedback_mailer:
    notification:
      to: support-klarschiff@bfpi.de
      subject: "Lob/Hinweis/Kritik zur Meldung #%{number}"
  issue_mailer:
    closed:
      subject: "#%{number}: abgeschlossen"
    delegation:
      subject: "Neue delegierte Meldungen"
    forward:
      subject: Weitergeleitete Meldung
    in_process:
      subject: "#%{number}: in Bearbeitung"
    inform_editorial_staff:
      subject: "%{title}: wichtige redaktionelle Hinweise"
    issue:
      subject: Weitergeleitete Meldung aus dem Beteiligungsportal Klarschiff MV
    responsibility:
      subject: "Neue Meldung #%{number} in Ihrer Zuständigkeit"
  test_mailer:
    test:
      subject: Test-Mail

consolidation: *default

production: *default

test: *default
