development: &default
  confirmation_base_url: https://www.klarschiff-mv.de/confirmations
  default:
    from: from@example.com
    exceptions_recipient: support-klarschiff@bfpi.de
    interceptions_recipient: support-klarschiff@bfpi.de

consolidation: *default

production: *default

test: *default
