development: &default
  default:
    from: from@example.com
    interceptions_recipient: support-klarschiff@bfpi.de
  issue_mailer:
    forward:
      subject: weitergeleiteter Vorgang
    issue:
      subject: weitergeleiteter Vorgang aus dem Beteiligungsportal Klarschiff von Schwerin
  test_mailer:
    test:
      subject: Test-Mail

consolidation: *default

production: *default

test: *default
