alpha:
  secret_key_base: <Secret-Key (pwgen -A 128 1)>

development:
  secret_key_base: <Secret-Key (pwgen -A 128 1)>

test:
  secret_key_base: <Secret-Key (pwgen -A 128 1)>

consolidation:
  secret_key_base: <Secret-Key (pwgen -A 128 1)>

production:
  secret_key_base: <Secret-Key (pwgen -A 128 1)>
