development: &default
  geocodr:
    address_object_group: Adresse HRO
    address_search_class: address_hro
    api_key: 1234567890abcdefghijklmnopqrstuv
    localisator: rostock # darf leer sein
    parcel_object_group: Flurstück
    parcel_search_class: parcel
    places_object_group: Adresse
    places_search_class: address
    property_owner_object_group: Flurstückseigentümer
    property_owner_search_class: property_owner
    proxy:
    url: https://geo.sv.rostock.de/geocodr/query?
  geoportal:
    enabled: true
    name: Geoport.HRO
    scale: 1508
    url: https://geo.sv.rostock.de/geoport?poi[point]=%{lon},%{lat}&poi[scale]=%{scale}&poi[label]=%{title}
  group:
    main_user_optional: true
  instance:
    relative_url_root: /backoffice
    name: Klarschiff.HRO
    city_long: Hanse- und Universitätsstadt Rostock
    city_short: Rostock
    frontend_url: https://www.klarschiff-hro.de/
    parent_instance_url: https://www.klarschiff-mv.de/
    show_help: false
    show_contact_before_login: false
    show_imprint_before_login: true
    validate_privacy_policy: false
    auth_code_gui_access_for_external_participants: true
    manage_categories: false
    log_issue_mailer_forward: false
  issue:
    status_note_max_length: 500
  job:
    lead_time: 2
  map:
    center: [1343496, 7197537]
    max_zoom: 19
    zoom: 12
    tile_layers:
      -
        id: karte
        url: https://www.orka-mv.de/geodienste/orkamv/tiles/1.0.0/orkamv/GLOBAL_WEBMERCATOR/{z}/{x}/{y}.png
        visible: true
        attribution: >
          Kartenbild © Hanse- und Universitätsstadt Rostock (<a rel="license" target="_blank" href="https://creativecommons.org/licenses/by/4.0/deed.de">CC BY 4.0</a>) | Kartendaten © OpenStreetMap (<a rel="license" target="_blank" href="https://opendatacommons.org/licenses/odbl/">ODbL</a>) und LkKfS-MV
      -
        id: luftbild
        url: https://geo.sv.rostock.de/geodienste/luftbild_mv-20/tiles/1.0.0/hro.luftbild_mv-20.luftbild_mv-20/GLOBAL_WEBMERCATOR/{z}/{x}/{y}.png
        visible: false
        attribution: >
          Luftbild © <a rel="license" target="_blank" href="https://www.geoportal-mv.de/portal/Geowebdienste">GeoBasis-DE/M-V</a>
    wms_layers:
      -
        id: poi
        url: https://geo.sv.rostock.de/geodienste/klarschiff-poi/wms?
        projection: EPSG:3857
        content: hro.klarschiff-poi.abfallbehaelter,hro.klarschiff-poi.ampeln,hro.klarschiff-poi.beleuchtung,hro.klarschiff-poi.brunnen,hro.klarschiff-poi.denkmale,hro.klarschiff-poi.hundetoiletten,hro.klarschiff-poi.kabelverteilerschraenke,hro.klarschiff-poi.recyclingcontainer,hro.klarschiff-poi.sitzgelegenheiten,hro.klarschiff-poi.sperrmuelltermine_oeffentlich,hro.klarschiff-poi.gemeinde-hro-invers
        format: image/png
        visible: true
  ldap:
    encryption: :simple_tls
    group_userlist: member
    host: rz200.sv.rostock.de
    password:
    port: 10389
    search_group: cn=Domain Users,cn=Users,o=ADMINHRO
    search_group_members: member
    search_user_attributes: SAMACCOUNTNAME,displayName
    search_user_base: o=ADMINHRO
    user_display_name: fullname
    user_email: mail
    user_first_name: givenname
    user_identifier: dn
    user_last_name: sn
    username:
  password:
    min_length: 8
    include_lowercase: true
    include_capital: true
    include_number: true
    include_special_character: false
    password_history: 0 # set 0 to disable password_history
  vote:
    min_requirement: 20

test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
