development: &default
  geocodr:
    address_object_group: Adresse HRO
    address_search_class: address_hro
    api_key: 1234567890abcdefghijklmnopqrstuv
    localisator: rostock # darf leer sein
    parcel_object_group: Flurst체ck
    parcel_search_class: parcel
    places_object_group: Adresse
    places_search_class: address
    property_owner_object_group: Flurst체ckseigent체mer
    property_owner_search_class: property_owner
    proxy:
    url: https://geo.sv.rostock.de/geocodr/query?
  geoportal:
    enabled: true
    name: Geoport.HRO
    scale: 1508
    url: https://geo.sv.rostock.de/geoport?poi[point]=%{lon},%{lat}&poi[scale]=%{scale}&poi[label]=%{title}
  group:
    main_user_optional: true
  instance:
    relative_url_root: /backoffice
    name: Klarschiff.HRO
    city_long: Hanse- und Universit채tsstadt Rostock
    city_short: Rostock
    frontend_issue_url: https://www.klarschiff-hro.de/map?request=%d
    parent_instance_url: https://www.klarschiff-mv.de/
    show_help: false
    validate_privacy_policy: false
    auth_code_gui_access_for_external_participants: true
  issue:
    status_note_max_length: 500
  job:
    lead_time: 2
  map:
    center: [12.070739011240928, 54.11739716348975]
    max_zoom: 16
    zoom: 7
    layers:
      -
        id: orka
        url: https://www.orka-mv.de/geodienste/orkamv/wmts/orkamv/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png
        layer: orkamv
        resolutions: [27.024570517098006, 19.109257071294042, 13.512285258549001, 9.55462853564702, 6.7561426292745, 4.77731426782351, 3.3780713146372494, 2.3886571339117544, 1.6890356573186245, 1.1943285669558772, 0.8445178286593122, 0.5971642834779384, 0.422258914329656, 0.29858214173896913, 0.21112945716482798, 0.14929107086948457]
        matrix_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        matrix_set: epsg_25833
        visible: true
      -
        id: geodaten
        url: https://geo.sv.rostock.de/geodienste/luftbild_mv-20/wmts/hro.luftbild_mv-20.luftbild_mv-20/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png
        layer: geodatenmv
        resolutions: [27.024570517098006, 19.109257071294042, 13.512285258549001, 9.55462853564702, 6.7561426292745, 4.77731426782351, 3.3780713146372494, 2.3886571339117544, 1.6890356573186245, 1.1943285669558772, 0.8445178286593122, 0.5971642834779384, 0.422258914329656, 0.29858214173896913, 0.21112945716482798, 0.14929107086948457]
        matrix_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        matrix_set: epsg_25833
        visible: false
    wms_layers:
      -
        id: poi
        url: https://geo.sv.rostock.de/geodienste/klarschiff-poi/wms?
        content: hro.klarschiff-poi.abfallbehaelter,hro.klarschiff-poi.ampeln,hro.klarschiff-poi.beleuchtung,hro.klarschiff-poi.brunnen,hro.klarschiff-poi.denkmale,hro.klarschiff-poi.hundetoiletten,hro.klarschiff-poi.kabelverteilerschraenke,hro.klarschiff-poi.recyclingcontainer,hro.klarschiff-poi.sitzgelegenheiten,hro.klarschiff-poi.sperrmuelltermine_oeffentlich,hro.klarschiff-poi.gemeinde-hro-invers
        format: image/png
        visible: true
    projection_25833: [-464849.38, 5057815.8685756, 787494.89142433, 6310160.14]
  ldap:
    encryption: :simple_tls
    group_userlist: member
    host: rz200.sv.rostock.de
    password:
    port: 10389
    search_group: cn=Domain Users,cn=Users,o=ADMINHRO
    search_group_members: member
    search_user_attributes: SAMACCOUNTNAME,displayName
    search_user_base: o=ADMINHRO
    user_display_name: fullname
    user_email: mail
    user_first_name: givenname
    user_identifier: dn
    user_last_name: sn
    username:
  password:
    min_length: 8
    include_lowercase: true
    include_capital: true
    include_number: true
    include_special_character: false
    password_history: 0 # set 0 to disable password_history
  vote:
    min_requirement: 20

test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
