development: &default
  geocodr:
    address_object_group: Adresse HRO
    address_search_class: address_hro
    api_key: 5c5281c45c5f4a729e8ecdb716637859
    localisator: rostock # darf leer sein
    parcel_object_group: Flurst체ck
    parcel_search_class: parcel
    places_object_group: Adresse
    places_search_class: address
    property_owner_object_group: Flurst체ckseigent체mer
    property_owner_search_class: property_owner
    url: https://geo.sv.rostock.de/geocodr/query?
  group:
    main_user_optional: true
  instance:
    name: Klarschiff.HRO
    city_long: Hanse- und Universit채tsstadt Rostock
    city_short: Rostock
    frontend_issue_url: https://www.klarschiff-hro.de/map?request={issue_id}
    parent_instance_url: https://www.klarschiff-mv.de/
  job:
    lead_time: 2
  map:
    center: [12.070739011240928, 54.11739716348975]
    zoom: 7
    layers:
      -
        id: orka
        url: https://www.orka-mv.de/geodienste/orkamv/wmts/orkamv/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png
        layer: orkamv
        resolutions: [27.024570517098006, 19.109257071294042, 13.512285258549001, 9.55462853564702, 6.7561426292745, 4.77731426782351, 3.3780713146372494, 2.3886571339117544, 1.6890356573186245, 1.1943285669558772, 0.8445178286593122, 0.5971642834779384, 0.422258914329656, 0.29858214173896913, 0.21112945716482798, 0.14929107086948457]
        matrix_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        matrix_set: epsg_25833
    projection_25833: [-464849.38, 5057815.8685756, 787494.89142433, 6310160.14]
  ldap:
    encryption: :simple_tls
    group_userlist: member
    host: rz200.sv.rostock.de
    password:
    port: 10389
    search_group: cn=Domain Users,cn=Users,o=ADMINHRO
    search_group_members: member
    search_user_attributes: SAMACCOUNTNAME,displayName
    search_user_base: o=ADMINHRO
    user_display_name: fullname
    user_email: mail
    user_first_name: givenname
    user_identifier: dn
    user_last_name: sn
    username:
test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
