Eigentum: Die Fläche befindet sich nicht im Eigentum der Stadt.
Gehölzschnitt: Schnitt- und Fällmaßnahmen können gemäß Bundesnaturschutzgesetz (§ 39 Abs. 5) nur vom 01. Oktober bis 28. Februar durchgeführt werden. Der Hinweis ist vorgemerkt.
Lichtraumprofil: Die Einschränkung der Durchgangsbreite ist noch nicht wesentlich. Derzeit besteht kein Handlungsbedarf.
Pflegeerfordernis: Ihr Hinweis ist berechtigt. Er wird in die turnusmäßige Pflege/Säuberung eingeordnet.
Pflegezustand: Ihr Hinweis ist nicht berechtigt. Der Pflegezustand/Reinigungszustand entspricht der Pflegestandard-Einstufung.
Unmut: Ihr Hinweis zielt auf übergeordnete kommunalpolitische Belange ab. Eine Bearbeitung ist uns mittels dieses Mediums nicht möglich.
