name: Dependabot auto-merge

on:
  - pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  jslint:
    uses: ./.github/workflows/lint-js.yml
  erblint:
    uses: ./.github/workflows/lint-erb.yml
  stylelint:
    uses: ./.github/workflows/lint-css.yml
  rubocop:
    uses: ./.github/workflows/rubocop.yml
  test:
    uses: ./.github/workflows/test.yml
  dependabot-automerge:
    runs-on: ubuntu-latest
    needs:
      - jslint
      - erblint
      - stylelint
      - rubocop
      - test
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ ! contains(steps.metadata.outputs.dependency-names, 'bootstrap') }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr edit --add-label "automerge" "$PR_URL"
          gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

