name: Build and Push via Docker Compose

on:
  push:
    branches:
      - docker
      # - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR with GitHub Actions token
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build image with Docker Compose
        run: docker compose build backoffice

      - name: Push image with tags
        run: |
          IMAGE=$(docker compose config --format json | jq -r '.services.backoffice.image') 
          docker push "$IMAGE"

          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG="${IMAGE%:*}:${GITHUB_REF#refs/tags/}"
            docker tag "$IMAGE" "$TAG"
            docker push "$TAG"
          fi

      - name: Docker logout
        if: always()
        run: docker logout ghcr.io
