name: Build and Push via Docker Compose

on:
  push:
    branches:
      - docker
      # - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR with GitHub Actions token
        run: echo "${{ secrets.DOCKER_LOGIN_TOKEN }}" | docker login ghcr.io -u "${{ secrets.DOCKER_LOGIN_USER }}" --password-stdin

      - name: Build image with Docker Compose
        run: docker compose build

      - name: Push image with Docker Compose
        run: docker compose push
